### ISSUE TITLE
Design the landing page UI/UX in Figma

### ISSUE THREAD

**Issue by aether-flux** [DevSoc-Asansol2023/DevSoc-Landing#1]
## Issue Description
We need a detailed design of the landing page of the website of our club, DevSoc. Its preferred to be designed as a single-page website. The design is to be made in Figma, in the link given below. See the steps to be followed for more information.

## What is to be done
You do not need to design the complete webpage by yourself. When you request to get assigned, also provide which portion of the website you want to design. For example, you may choose to design only the hero section or the footer.
You can take a look at Dribbble, Behance, Awwwards etc. for inspiration.

## Steps to Complete

-   Request to get yourself assigned to the issue, along with providing your email used in Figma.
-   You will now be given access to the Figma file.
-   Go to https://www.figma.com/design/ax6G9a86UI1JvxOTyYe0gA/DEVSOC-Landing-Page?node-id=0-1&t=VXoFDR6hoSsWA3Sd-1 and unleash your creativity.
-   After you are done with your designing, download the Figma frame and add it to the 'designs' folder, with your name in the filename. If there is no 'designs' folder, create one.
-   Also, add your name to the contributors.txt file.

**Comment by dipsonishikha** [comment]
i would like to contribute. please assign issue to me.
i am interested to work on hero section.

Figma-:dipshikhasoni66@gmail.com

**Comment by 73LIX** [comment]
Please assign this issue to me.
I will do the hero section
Figma : chatgai.note@gmail.com

**Comment by Zayed-Ahmed-dev** [comment]
I would like to work on it
E-mail: zayedahmed745@gmail.com

**Comment by 221BProgrammer** [comment]
Please assign this issue to me.
Figma :- sinchanroy32@gmail.com

**Comment by Son7c** [comment]
Please assign this to me 
I want to work on the hero section of the landing page.
Email- souvikmajee039@gmail.com

**Comment by aether-flux** [comment]
73LIX, Zayed-Ahmed-dev and 221BProgrammer, also mention which part you want to design
##### Note: if one or more people are working on the same section, make separate frames in the Figma files for each of your design. 
##### Note: the frame you work on should be named after you, like [your name]-design or something similar

**Comment by 221BProgrammer** [comment]
I am designing the header part.

**Comment by aether-flux** [comment]
https://dribbble.com/shots/21526388-Modern-Houses-Company-Website
https://dribbble.com/shots/23090247-Videaste-Personal-Videographer-Portfolio-Landing-Page-Website
https://dribbble.com/shots/24407534-Dauernd-Creative-Design-Agency-Landing-Page-Website
https://styleshout.com/demo/?theme=mueller

##### Take a look at these designs for inspirations. This is the kind of look and vibes we're going for; a modern, elegant and professional look.

**Comment by aether-flux** [comment]
One more thing: Work on the designs for smaller screens as well, like make your design responsive for mobile screens too.

**Comment by AsifQamar** [comment]
please assign me this 
I want design footer section for this site
figma - asifqamar1832004@gmail.com

**Comment by aether-flux** [comment]
> please assign me this I want design footer section for this site figma - [asifqamar1832004@gmail.com](mailto:asifqamar1832004@gmail.com)

message again in the new issue I've created, this issue will be closed now.
