### ISSUE TITLE
About page for the site

### ISSUE THREAD

**Issue by Deepankar1484** [DevSoc-Asansol2023/DevSoc-Landing#10]
Hey @widewipe, 
I can handle the about page for the site. Just Assign me the task with ahacktoberfest Labeled and i shall do the contribution by tomorrow.

**Comment by aether-flux** [comment]
> Hey @widewipe, 
> I can handle the about page for the site. Just Assign me the task with ahacktoberfest Labeled and i shall do the contribution by tomorrow.

Okay I will assign you this issue. Send your Figma email here and request access to the Figma link, I will give the necessary permissions. 

Looking forward

**Comment by Deepankar1484** [comment]
Hello @widewipe,
I was contributing in the HTML and CSS part of the landing page. Please may you tell me why i need to share my figma email.

**Comment by aether-flux** [comment]
Oh okay, I thought you will be designing the About section. 
No issues then, you may start with your work.
