### ISSUE TITLE
enhancing the contact-us page about page and enhance the navbar

### ISSUE THREAD

**Issue by dhruv-4444** [DevSoc-Asansol2023/DevSoc-Landing#12]
hey @DevSoc-Asansol2023
I will able to help you enhancing the ui for contact us page,about and navbar for better user engagement and will also make that responsive so that user can access it from any device.
assign me this task, with hacktoberfest labels.
Thanks in Advance

**Comment by aether-flux** [comment]
Sorry for the late reply. If you are still available, please do contribute to the repo. I will assign you this issue.

**Comment by dhruv-4444** [comment]
Hey @xerctia , I have contributed to the repo. please check the changes done and merge the pull request.
